name: Build webpack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo NODE_ENV=production >> .env
      - run: echo NETWORK='ropsten' >> .env
      - run: echo beacon=69420753206121746f776e206f652deadbeef69420 >> .env
      - run: yarn
      - run: wget https://powers-of-tau.s3.amazonaws.com/pots.zip
      - run: unzip pots.zip
      - run: yarn compile:circom sig-check 20
      - run: yarn compile:circom hash-check 15
      - run: yarn compile:circom hash-check-bits 20
      - run: yarn build
      - run: echo confessions.digital >> ./dist/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
